from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

print('---- lemmatize ----')
wnl = WordNetLemmatizer()
print(wnl.lemmatize('generous'))
print(wnl.lemmatize('dogs'))
print(wnl.lemmatize('doing'))
print(wnl.lemmatize('representing'))
print(wnl.lemmatize('representing', pos="v"))
print(wnl.lemmatize('shopping'))
print(wnl.lemmatize('shopping', pos="v"))
print(wnl.lemmatize('loafers'))
print(wnl.lemmatize('screwed'))
print(wnl.lemmatize('women'))
print(wnl.lemmatize('children'))
print(wnl.lemmatize('mobile'))
print('---- stem ----')
stemmer = PorterStemmer()
print(stemmer.stem('generous'))
print(stemmer.stem('dogs'))
print(stemmer.stem('doing'))
print(stemmer.stem('representing'))
print(stemmer.stem('shopping'))
print(stemmer.stem('loafers'))
print(stemmer.stem('screwed'))
print(stemmer.stem('women'))
print(stemmer.stem('children'))
print(stemmer.stem('mobile'))